### ISSUE TITLE
does it work with a PAX S80

### ISSUE THREAD

**Issue by jjone** [AccelerateNetworks/PHPax#3]
HI, thefinn93

Need your help please.
I want to set it up for testing it with a PAX S80 terminal.?
I see that lib folder is not in your repository

Thank you very much

Justin

**Comment by danry25** [comment]
Hi jjone,

I believe you'll need either a Pax S300, MT30, or Px7, as the Pax S80 is a standalone terminal, not a multilane pinpad.

The S300 is the same price as the Pax S80 itself, plus you don't need an SP20 to pair with it, so it is cheaper overall.

**Comment by jjone** [comment]
Thank you very much  danry25, I will get a S30

I don't see lib folder in the  repository. is it missing or not required?

Thank you again.
Justin

**Comment by danry25** [comment]
Yeah, get a S300. As to libs, all these pinpads use the same API, the only difference is font size, which we've only dealt with when pushing items purchased onto the screen of the pinpad.

**Comment by jjone** [comment]
great. is the API lib only available from PAX and sign a NDA ? 
Can you upload it to your Repository?

Thank you very much

Justin

**Comment by thefinn93** [comment]
What lib folder are you talking about? Pax shipped us a bunch of useless, closed source, windows-only crap when we signed their NDA, and a barely readable PDF with the communication protocol. This library is the result of my parsing of that communication protocol document

**Comment by jjone** [comment]
Hi thefinn93,

These 2 lines in pax.php 

include_once(dirname(**FILE**).'/../../../lib/AutoLoader.php');
use Guzzle\Http\Client;

Thank you very much

Justin

**Comment by thefinn93** [comment]
Ah, whoops! That's part of the larger system we're using it in. I'm pretty new building to PHP libraries and still kind of leaning the ropes. I've removed that line, make sure that `Guzzle\Http\Client` is available before it runs though

**Comment by jjone** [comment]
Great. Thank you very much thefinn93!
Justin

**Comment by thefinn93** [comment]
I kind of forgot about this repo and ended up developing the library as a component of a larger system, so I'm bringing it back in here slowly. Be aware that I just re-arranged most of the files to have a more logical directory structure

**Comment by jjone** [comment]
great. This repo is really helpful!
Justin

**Comment by thefinn93** [comment]
Great, glad to hear it. I'm gonna close this issue but if you have any other questions feel free to open issues or stop by `#AccelerateNetworks` on Freenode
